name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: 3.9
            toxenv: py39
          - python-version: 3.10
            toxenv: py310
          - python-version: 3.11
            toxenv: py311
          - python-version: 3.12
            toxenv: py312
          - python-version: 3.13
            toxenv: py313
          - python-version: 3.14
            toxenv: py314
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        env:
          TOXENV: ${{ matrix.toxenv }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: tox
